<?php

/**
 * @file
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\datastore\LifeCycle\Data as LifeCycle;
use Drupal\common\Exception\DataNodeLifeCycleEntityValidationException;
use Drupal\metastore\NodeWrapper\Data;

/**
 * Implements hook_ENTITY_TYPE_predelete().
 */
function datastore_node_predelete(EntityInterface $entity) {
  try {
    (new LifeCycle(new Data($entity)))->predelete();
  }
  catch (DataNodeLifeCycleEntityValidationException $e) {
  }
}
