<?php

namespace Drupal\Tests\dkan;

use Composer\Autoload\ClassLoader;
use Drupal\Core\DrupalKernel;
use Drupal\metastore\Reference\Dereferencer;
use Drupal\node\Entity\Node;
use Drupal\Tests\UnitTestCase;
use Symfony\Component\HttpFoundation\Request;

class DatasetTest extends UnitTestCase {

  public function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
    $appRoot = __DIR__ . '/../../../../..';
    $classLoader = new ClassLoader();
    $kernel = new DrupalKernel('prod', $classLoader, TRUE, $appRoot);
    $kernel->handle(new Request());
  }


  public function test() {
    $downloadUrl = "http://spatialkeydocs.s3.amazonaws.com/FL_insurance_sample.csv.zip";
    $dataset = '
    {
      "title": "Test #1",
      "description": "Yep",
      "identifier": "123",
      "accessLevel": "public",
      "modified": "06-04-2020",
      "keyword": ["hello"],
        "distribution": [
          {
            "title": "blah",
            "downloadURL": "' . $downloadUrl . '",
            "mediaType": "text/csv"
          }
        ]
    }';

    /* @var $service \Drupal\metastore\Service */
    $service = \Drupal::service('dkan.metastore.service');

    $identifier = $service->post('dataset', $dataset);
    $this->assertEquals("123", $identifier);

    drupal_static('metastore_dereference_method', Dereferencer::DEREFERENCE_OUTPUT_REFERENCE_IDS);

    $datasetWithReferencesJson = $service->get('dataset', '123');
    $datasetWithReferences = json_decode($datasetWithReferencesJson);
    $this->assertEquals(
      $downloadUrl,
      $datasetWithReferences->distribution[0]->data->downloadURL->data->filePath
    );
  }

  private function removeAllNodes() {
    $nodes = Node::loadMultiple();
    foreach ($nodes as $node) {
      $node->delete();
    }
  }

  private function removeAllMappedFiles() {
    /* @var $filemappertable \Drupal\metastore\Storage\FileMapperDatabaseTable */
    $filemappertable = \Drupal::service('dkan.metastore.file_mapper_database_table');
    foreach ($filemappertable->retrieveAll() as $id) {
      $filemappertable->remove($id);
    }
  }

  public function tearDown() {
    parent::tearDown(); // TODO: Change the autogenerated stub
    $this->removeAllNodes();
    $this->removeAllMappedFiles();
  }

}
